# Generated by Django 4.0 on 2021-12-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwordresetcodes',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
