# Generated by Django 4.0 on 2021-12-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='economy',
            name='Date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='economy',
            name='Amount',
            field=models.PositiveIntegerField(),
        ),
    ]
