# Generated by Django 4.0 on 2021-12-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0004_remove_economy_user_economy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economy',
            name='user',
        ),
        migrations.AddField(
            model_name='economy',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='todoer',
            name='user',
        ),
        migrations.AddField(
            model_name='todoer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
